import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Link, useNavigate } from 'react-router-dom'
import { FiTarget, FiTrendingUp, FiAward, FiBookOpen, FiCheckCircle, FiStar, FiArrowRight } from 'react-icons/fi'
import toast from 'react-hot-toast'

const About = () => {
  const navigate = useNavigate()

  useEffect(() => {
    // Smooth scroll to top when component mounts
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [])

  const features = [
    {
      icon: FiTarget,
      title: "AI-Powered Questions",
      description: "Get personalized interview questions generated by advanced AI technology tailored to your specific role and experience level.",
      color: "from-blue-600 to-cyan-600"
    },
    {
      icon: FiTrendingUp,
      title: "Instant Feedback",
      description: "Receive real-time analysis and constructive feedback on your answers to improve your interview performance.",
      color: "from-purple-600 to-pink-600"
    },
    {
      icon: FiAward,
      title: "Performance Scoring",
      description: "Track your progress with detailed scoring and comprehensive performance metrics.",
      color: "from-green-600 to-emerald-600"
    },
    {
      icon: FiBookOpen,
      title: "Expert Guidance",
      description: "Access expert tips and best practices to excel in any interview scenario.",
      color: "from-orange-600 to-red-600"
    }
  ]

  const stats = [
    { number: "10,000+", label: "Questions Generated", description: "By our AI system" },
    { number: "95%", label: "Success Rate", description: "Users who improved their skills" },
    { number: "500+", label: "Companies", description: "Where our users got hired" },
    { number: "4.8/5", label: "User Rating", description: "Based on user feedback" }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <motion.div
            className="text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-5xl font-bold text-gray-900 mb-6">
              About InterviewAI
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
              InterviewAI is an intelligent platform designed to help job seekers and students prepare 
              for real-world interviews using cutting-edge AI technology. Our mission is to make 
              interview preparation accessible, effective, and personalized for everyone.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
              <Link
                to="/signup"
                className="px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-semibold hover:shadow-xl transition-all"
              >
                Get Started Free
                <FiArrowRight className="ml-2" size={20} />
              </Link>
              <Link
                to="/dashboard"
                className="px-8 py-4 bg-white text-gray-700 rounded-xl font-semibold border border-gray-200 hover:shadow-lg transition-all"
              >
                View Dashboard
              </Link>
            </div>
          </motion.div>
        </div>
        
        {/* Background decoration */}
        <div className="absolute top-0 left-0 w-full h-full pointer-events-none">
          <div className="absolute top-20 left-10 w-72 h-72 bg-blue-300 rounded-full opacity-20 blur-3xl"></div>
          <div className="absolute top-40 right-10 w-96 h-96 bg-purple-300 rounded-full opacity-20 blur-3xl"></div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Trusted by Thousands
            </h2>
            <p className="text-gray-600 text-lg max-w-2xl mx-auto">
              Join thousands of successful candidates who improved their interview skills with InterviewAI
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                className="text-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <div className="text-4xl font-bold text-blue-600 mb-2">
                  {stat.number}
                </div>
                <div className="text-gray-900 font-semibold mb-1">
                  {stat.label}
                </div>
                <div className="text-gray-600 text-sm">
                  {stat.description}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Powerful Features
            </h2>
            <p className="text-gray-600 text-lg max-w-2xl mx-auto">
              InterviewAI provides comprehensive tools and features to help you succeed in any interview
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                className="bg-white rounded-xl p-6 shadow-lg border border-gray-100 hover:shadow-xl transition-shadow"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                whileHover={{ y: -5 }}
              >
                <div className={`w-12 h-12 bg-gradient-to-r ${feature.color} rounded-lg flex items-center justify-center mb-4`}>
                  <feature.icon className="text-white" size={24} />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600 text-sm leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-gray-600 text-lg max-w-2xl mx-auto">
              Get started with InterviewAI in just a few simple steps
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {[
              { step: 1, title: "Create Account", description: "Sign up for free and set up your profile", icon: "👤" },
              { step: 2, title: "Set Interview Parameters", description: "Choose your role and experience level", icon: "⚙️" },
              { step: 3, title: "Practice Questions", description: "Answer AI-generated interview questions", icon: "💬" },
              { step: 4, title: "Get Feedback", description: "Receive instant AI feedback and scoring", icon: "📊" }
            ].map((step, index) => (
              <motion.div
                key={index}
                className="text-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                  {step.step}
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {step.title}
                </h3>
                <p className="text-gray-600 text-sm">
                  {step.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl font-bold text-white mb-4">
              Success Stories
            </h2>
            <p className="text-blue-100 text-lg max-w-2xl mx-auto">
              Hear from professionals who landed their dream jobs with InterviewAI
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                name: "Sarah Chen",
                role: "Software Engineer",
                company: "Google",
                quote: "InterviewAI helped me prepare for technical interviews at Google. The AI feedback was incredibly detailed and helped me improve my problem-solving approach.",
                rating: 5
              },
              {
                name: "Michael Johnson",
                role: "Product Manager",
                company: "Meta",
                quote: "The mock interviews were spot-on! I felt confident and prepared for my actual interviews at Meta. Got the job!",
                rating: 5
              },
              {
                name: "Emily Davis",
                role: "Data Scientist",
                company: "Amazon",
                quote: "InterviewAI's AI questions were challenging but fair. The feedback helped me identify areas I needed to work on.",
                rating: 5
              }
            ].map((testimonial, index) => (
              <motion.div
                key={index}
                className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <div className="flex items-center mb-4">
                  <div className="w-12 h-12 bg-gradient-to-r from-blue-400 to-purple-400 rounded-full flex items-center justify-center text-white font-bold">
                    {testimonial.name.charAt(0)}
                  </div>
                  <div className="text-left ml-4">
                    <h4 className="text-white font-semibold">{testimonial.name}</h4>
                    <p className="text-blue-100 text-sm">{testimonial.role} at {testimonial.company}</p>
                    <div className="flex mt-1">
                      {[...Array(testimonial.rating)].map((_, i) => (
                        <FiStar key={i} className="text-yellow-400" size={14} fill="currentColor" />
                      ))}
                    </div>
                  </div>
                </div>
                <p className="text-white italic">
                  "{testimonial.quote}"
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Ready to Ace Your Next Interview?
            </h2>
            <p className="text-gray-600 text-lg mb-8 max-w-2xl mx-auto">
              Join thousands of successful candidates who used InterviewAI to land their dream jobs
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/signup"
                className="px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-semibold hover:shadow-xl transition-all"
              >
                Start Free Trial
                <FiArrowRight className="ml-2" size={20} />
              </Link>
              <Link
                to="/dashboard"
                className="px-8 py-4 bg-white text-gray-700 rounded-xl font-semibold border border-gray-200 hover:shadow-lg transition-all"
              >
                View Demo
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  )
}

export default About
